version: "3.3"

services:
  gateway:
    image: axeldf/lama-activity-4:gateway_legacy
    restart: always
    ports:
      - "8080:8080"
    network_mode: host
  authService:
    image: axeldf/lama-activity-4:authentication_legacy
    restart: always
    ports:
      - "8081:8081"
  cardService:
    image: axeldf/lama-activity-4:card-service
    restart: always
    ports:
      - "8082:8082"
  playerService:
    image: axeldf/lama-activity-4:player-service
    restart: always
    ports:
      - "8083:8083"
  marketService:
    image: axeldf/lama-activity-4:market-service
    restart: always
    ports:
      - "8084:8084"
  roomService:
    image: axeldf/lama-activity-4:game-service
    restart: always
    ports:
      - "8085:8085"
  gameService:
    image: axeldf/lama-activity-4:room-service
    restart: always
    ports:
      - "8086:8086"