logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: AuthService
#        uri: http://localhost:8081
#        predicates:
#        - Path=/auth/**
#      - id: cardService
#        uri: http://localhost:8082
#        predicates:
#        - Path=/cards/**
#      - id: playerService
#        uri: http://localhost:8083
#        predicates:
#        - Path=/players/**
#      - id: marketService
#        uri: http://localhost:8084
#        predicates:
#        - Path=/market/**
#      - id: gameService
#        uri: http://localhost:8085
#        predicates:
#        - Path=/games/**
#      - id: roomService
#        uri: http://localhost:8086
#        predicates:
#        - Path=/rooms/**
